import os

DATABASE_URL = os.getenv("DATABASE_URL")
DB_POOL_MIN_SIZE = 1
DB_POOL_MAX_SIZE = 3

SHELLY_DEVICE_ID = "shellypro4pm-a0dd6c9ef474"

GAP_THRESHOLD_MINUTES = 4
MIN_CYCLE_DURATION_MINUTES = 2
DEFAULT_DAYS_HISTORY = 30
